name: 'create README.md for all Docker images'
author: '11notes'
description: 'This action will create a README.md for all my Docker images'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  sarif_file: 
    description: 'the grype sarif output'
    required: true
runs:
  using: 'node20'
  main: 'index.js'