name: 'action-docker-readme'
author: '11notes'
description: 'This action will create a README.md for all my Docker images'
branding:
  icon: 'book-open'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'